// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBry00LSqGVK_6iHAxC5HuqXUTgtkdXLVI',
    appId: '1:576629838865:web:0c48323eb9bd73eb638db0',
    messagingSenderId: '576629838865',
    projectId: 'mywhvaus',
    authDomain: 'mywhvaus.firebaseapp.com',
    storageBucket: 'mywhvaus.firebasestorage.app',
    measurementId: 'G-69P0PLFS5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0MS9Wc9mfOgqehnYGZ2C8ucPcDnYSRFo',
    appId: '1:576629838865:android:1d2bd72cdf881a79638db0',
    messagingSenderId: '576629838865',
    projectId: 'mywhvaus',
    storageBucket: 'mywhvaus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ufjaFs-n8Z_jnaRgeqGZjeuVS4zKdKk',
    appId: '1:576629838865:ios:ce4312aceae72465638db0',
    messagingSenderId: '576629838865',
    projectId: 'mywhvaus',
    storageBucket: 'mywhvaus.firebasestorage.app',
    iosBundleId: 'com.example.mywhv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ufjaFs-n8Z_jnaRgeqGZjeuVS4zKdKk',
    appId: '1:576629838865:ios:ce4312aceae72465638db0',
    messagingSenderId: '576629838865',
    projectId: 'mywhvaus',
    storageBucket: 'mywhvaus.firebasestorage.app',
    iosBundleId: 'com.example.mywhv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBry00LSqGVK_6iHAxC5HuqXUTgtkdXLVI',
    appId: '1:576629838865:web:eb10661d30f85c28638db0',
    messagingSenderId: '576629838865',
    projectId: 'mywhvaus',
    authDomain: 'mywhvaus.firebaseapp.com',
    storageBucket: 'mywhvaus.firebasestorage.app',
    measurementId: 'G-JD6BW2JXND',
  );

}